<?php

/**
 * Pivlu Analytics - Open source and privacy-friendly web analytics.
 * https://analytics.pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@pivlu.com>
 *  * 
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Schema;
use Artisan;
use App\Models\Config;


class UpdateCommand extends Command
{


    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'pivlu:update';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Allows to update the app directly through CLI';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {

        if (!Schema::hasTable('config')) {
            $this->error('Pivlu Analytics is not installed!');
            $this->line('You can install Pivlu using "pivlu:install" command.');
            return;
        }

        if (!Config::config('installed_at')) {
            $this->error('Pivlu is not installed!');
            $this->line('You can install Pivlu using "pivlu:install" command.');
            return;
        }

        $this->line('Update database tables');
        Artisan::call('migrate');
        
        Config::update_config('updated_at', now());
        $this->info('The update was successful!');
    }
}
