<?php

/**
 * Pivlu Analytics - Open source and privacy-friendly web analytics.
 * https://analytics.pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@pivlu.com>
 *  * 
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */


declare(strict_types=1);

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Account\UserController as UserController;
use App\Http\Controllers\Account\SiteController as SiteController;
use App\Http\Controllers\Account\StatsController as StatsController;
use App\Http\Controllers\Account\ReportController as ReportController;
use App\Http\Controllers\LogoutController as LogoutController;

Route::post('logout', [LogoutController::class, 'logout'])->name('logout');

Route::get('account', [SiteController::class, 'index'])->name('user');

Route::get('/', [SiteController::class, 'index'])->middleware('auth')->name('admin');

Route::prefix('account')->group(function () {

    // Dashboard
    Route::get('dashboard', [SiteController::class, 'index'])->name('dashboard');

    // Stats
    Route::get('sites/{code}/page-stats/{hash}', [StatsController::class, 'page_stats'])->name('site.page_stats')->where(['hash' => '[a-zA-Z0-9]+']);
    Route::get('sites/{code}/pages', [StatsController::class, 'pages'])->name('site.pages')->where(['code' => '[a-zA-Z0-9]+']);
    Route::get('sites/{code}/visitors', [StatsController::class, 'visitors'])->name('site.visitors')->where(['code' => '[a-zA-Z0-9]+']);
    Route::get('sites/{code}/reports', [ReportController::class, 'index'])->name('site.reports')->where(['code' => '[a-zA-Z0-9]+']);
    Route::get('sites/{code}', [StatsController::class, 'index'])->name('site.show')->where(['code' => '[a-zA-Z0-9]+']);

    // Sites
    Route::get('sites/{code}/config', [SiteController::class, 'config'])->name('site.config')->where(['code' => '[a-zA-Z0-9]+']);
    Route::put('sites/{code}', [SiteController::class, 'update'])->name('site.update')->where(['code' => '[a-zA-Z0-9]+']);
    Route::delete('sites/{code}', [SiteController::class, 'destroy'])->name('site.delete')->where(['code' => '[a-zA-Z0-9]+']);
    Route::get('sites', [SiteController::class, 'index'])->name('sites.index');
    Route::post('sites', [SiteController::class, 'store'])->name('sites.store');
    
    // profile
    Route::get('profile', [UserController::class, 'profile'])->name('profile');
    Route::post('profile', [UserController::class, 'update_profile']);
    Route::delete('profile/delete-avatar', [UserController::class, 'delete_avatar'])->name('profile.delete_avatar');
});
