<?php

/**
 * Pivlu Analytics - Open source and privacy-friendly web analytics.
 * https://analytics.pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@pivlu.com>
 *  * 
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class LogSession extends Model
{

    protected $table = 'log_session';

    protected $fillable = ['hash', 'visitor_id', 'site_id', 'page_id', 'referrer', 'referrer_host', 'first', 'last', 'scroll_percent', 'seconds_min', 'event_id', 'created_at'];

    public $timestamps = false;

    protected $appends = ['count_sessions', 'time_diff_human'];

    public function site()
    {
        return $this->belongsTo(Site::class, 'site_id', 'id');
    }

    public function visitor()
    {
        return $this->belongsTo(LogVisitor::class, 'visitor_id', 'id');
    }

    public function page()
    {
        return $this->belongsTo(LogPage::class, 'page_id', 'id');
    }

    public function event()
    {
        return $this->belongsTo(Event::class, 'event_id', 'id');
    }


    public function getCountSessionsAttribute()
    {
        $count_sessions = LogSession::where('page_id', $this->page_id)->count();
        return $count_sessions;
    }

    public function getTimeDiffHumanAttribute()
    {
        $created_at = LogSession::where('id', $this->id)->value('created_at');
        $dt = Carbon::parse($created_at);
        $dt->locale('ro');

        return $dt->diffForHumans();
    }
}
