<?php

/**
 * Pivlu Analytics - Open source and privacy-friendly web analytics.
 * https://analytics.pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@pivlu.com>
 *  * 
 *  DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class LogVisitor extends Model
{

    protected $table = 'log_visitors';

    protected $fillable = [
        'site_id',
        'hash',
        'ip',
        'device_type',
        'platform_family',
        'platform_name',
        'platform_version',
        'browser_family',
        'browser_name',
        'browser_version',
        'device_family',
        'device_model',
        'screen_size',
        'count_visits',
        'geo_cc',
        'geo_country',
        'geo_region',
        'geo_region_name',
        'geo_city',
        'geo_isp',
        'geo_lat',
        'geo_long',
        'created_at'
    ];

    protected $appends = ['last_5_sessions', 'time_diff_human'];

    public function site()
    {
        return $this->belongsTo(Site::class, 'site_id', 'id');
    }

    public function sessions()
    {
        return $this->hasMany(LogSession::class, 'visitor_id', 'id');
    }

    public function getLast5SessionsAttribute()
    {
        return $this->sessions()->take(3)->get();
    }


    public function getTimeDiffHumanAttribute()
    {
        $created_at = LogVisitor::where('id', $this->id)->value('created_at');
        $dt = Carbon::parse($created_at);
        $dt->locale('ro');

        return $dt->diffForHumans();
    }
}
